spring.application.name=JWT_exp9

spring.datasource.url=jdbc:mysql://localhost:3306/ramjava
spring.datasource.username=root
spring.datasource.password=Meeku05@
spring.jpa.show-sql=true
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate=ERROR
spring.jpa.hibernate.ddl-auto=update
server.port=8081